### ISSUE TITLE
How would you implement Server Side Rendering ?

### ISSUE THREAD

**Issue by Kroonax** [rishipr/mern-auth#1]
Hey, I love your boilerplate and am actually using it for a project !
Overall everything is exactly how I want it to be, except one thing... SSR !

I am actually having some trouble to implement SSR with your React app. Do you have any idea on how we could upgrade it with SSR ?

**Comment by rishipr** [comment]
> I am actually having some trouble to implement SSR with your React app. Do you have any idea on how we could upgrade it with SSR

@Kroonax I'm actually not too familiar with SSR as a fairly new React/full-stack developer. Apologies for not being able to help more, but thrilled to hear that you are using this for a project. If you are able to figure out this issue please do let me know, I'd love to hear the solution. I'll look into SSR myself as well as it is a topic I have not covered before.

**Comment by rishipr** [comment]
Look into Next.js for Server Side React instead of using Create React App for bootstrapping. Traversy has a solid video on it: https://www.youtube.com/watch?v=IkOVe40Sy0U
