### ISSUE TITLE
Does not work on Heroku

### ISSUE THREAD

**Issue by mohsinht** [rishipr/mern-auth#10]
**Context:** The app is working fine on the localhost. I've tested APIs and React components and the result was flawless.

**Problem:** 
Followed all the steps from this video https://www.youtube.com/watch?v=71wSzpLyW9k and uploaded the app on Heroku.
The landing page works fine but the resources (like style.css, logo files etc.) are inaccessible from the app. The pages
somename.herokuapp.com/login and  somename.herokuapp.com/register return 'Internal Server Error'.

What could be the possible fix for this?

**Comment by ya332** [comment]
Having the same issue. Any thoughts?

**Comment by mohsinht** [comment]
Add a 'homepage' value in package.json and It'll work.

Follow these steps: https://create-react-app.dev/docs/deployment
