### ISSUE TITLE
I want to pass the Id of the user in URL to make axios.get request,How can I do that?

### ISSUE THREAD

**Issue by BradPrit09** [rishipr/mern-auth#15]
@rishipr 

First of all, this was a great article .

I have learnt react-redux from this but I am having issue when I need to pass the ID of the user in the URL,
- [x] I need little bit of understanding here,I am unable to do it?
- [x] Is there any method so that I can use the ID of the signed IN user in making axios.get request to my API.
- [x] Where I need to change the files ?
Please someone can explain?

**Comment by rishipr** [comment]
Yes, in your `mapStateToProps`, map your `user` object in Redux to your component's props. Then, whenever you call a Redux action that invokes an axios request in your component, pass in `this.props.user.id` or the entire `user` object as a parameter. You'll then have access to it in your Redux action (just make sure to edit the action so it accepts the new parameter). In the URL in your Axios request, you can use an object literal such as `axios.delete`(`/api/users/delete/${user_id}`) to reference the user id parameter, for example.

**Comment by BradPrit09** [comment]
Thanks Rishi great help.

**Comment by BradPrit09** [comment]
@rishipr 
I need help . Please have a look .
I mapped the mapStateToProps like this .

```
const mapStateToProps = state => ({
  auth: state.auth,
  user: state.user,
  errors: state.errors
});
```

from my component and  when i do axios request in authAction , Do I need to pass directly user directly like

```
export const registerDevice = (userData, history) => dispatch => {
  axios
    .post("/api/users/addDevice/${user_id}", userData)
    .then(res => history.push("/Comment"))
    .catch(err =>
      dispatch({
        type: GET_ERRORS,
        payload: err.response.data
      })
    );
};
```

My back-end code is developed such that it takes farm id also,I can make a postman request it's working but I am unable to integrate with front-end part ,little.

```
//Router for Device Addition in a Specific Farm
//:id@ User Id
//:farmID@ Farm that we want to add the Device.  
router.post("/addDevice/:id/:farmID",(req,res) => {
  const deviceName=req.body.deviceName;
  const deviceType=req.body.deviceType;
  const description=req.body.description;
  const deviceLocation=req.body.deviceLocation;
  const Parameter=req.body.Parameter;
  const Topic=("sagita/"+User.name+"/"+req.params.farmID+"/"+deviceName+"/"+deviceLocation+"/"+Parameter);
  User.findByIdAndUpdate(req.params.id, 
    { $push: { "farm.$[farm].device": {deviceName,deviceType,description,deviceLocation,Parameter,Topic} },
     $currentDate:{lastModified:true,"deviceModified":{$type:"timestamp"}} },
      { arrayFilters: [ { "farm._id": req.params.farmID } ],upsert: true, safe: true, new: true, multi: false},
        function (err, updatedFarm)
         {
          if (err)
          console.log(err);
          res.json({success:true,message:"Farm updated! Roger_That.",body:updatedFarm});
          }); 
   User.aggregate([
    {$group:{ _id:"$device",data:{$push:"$Topic"}} },
  
    {$out:"Data Bucket",}
  ]);
  
});
```
