### ISSUE TITLE
REDUX_DEVTOOLS_EXTENSION

### ISSUE THREAD

**Issue by mmunier44** [rishipr/mern-auth#4]
For some reason I was getting an undefined apply error and after looking around it looks like REDUX_DEVTOOLS_EXTENSION has to be slightly changed, so instead of whats is on  line 14 of store.js I applied the below and was able to get through the error.

``` js
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__() || compose
```

**Comment by jmvan** [comment]
This fixed my issue

**Comment by rishipr** [comment]
Fixed in master!
