### ISSUE TITLE
Mobile web version not rendering

### ISSUE THREAD

**Issue by justinkchen** [rishipr/mern-auth#5]
Not sure if this is an issue with the setup here or something else but my site doesn't render when loading it via moweb (deployed via heroku). any thoughts?

**Comment by justinkchen** [comment]
Fixed by redux devtools https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup

**Comment by rishipr** [comment]
Should be fixed, added Redux compose to store.js
