### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by efendic** [rishipr/mern-auth#7]
Hello brother,

First let me say thank you for this app, it's a really good starter for a project I have. Now to my question, as one of my tasks is to deploy this somewhere and I picked heroku, could you please help me by adding a production configuration to this app? I tried almost all day yesterday and I will continue trying today, so far no success. I've followed the video you provided but no go. Fixed few of the issues I stumbled upon the way. Now the error I get is as follows:

"at=info method=GET path="/" host=still-castle-16013.herokuapp.com request_id=4d24fd1e-2d01-4f61-bdf2-cd1db48c68de fwd="31.176.251.67" dyno=web.1 connect=0ms service=13ms status=404 bytes=380 protocol=https
2019-05-22T07:57:06.298913+00:00 app[web.1]: Error: ENOENT: no such file or directory, stat '/app/client/build/index.html'"

I've pasted all the code the guy from the video you have left, as the code structure seems to be the same, but I get this path error and I'm not sure how to fix it. This is the code I've added in server.js above the const port part:

// Serve static assets in in production
if (process.env.NODE_ENV === 'production') {
  // Set static folder
  app.use(express.static('client/build'));

  app.get('*', (req, res) => {
    res.sendFile(path.resolve(__dirname, 'client', 'build', 'index.html'));
  });
}

Thank you for your help brother!

**Comment by efendic** [comment]
Update: I actually managed to make it deploy and build correctly on heroku, but now I can't run it locally... Working on that now.

**Comment by rishipr** [comment]
What errors are you running into while running it locally? @efendic

**Comment by efendic** [comment]
Hello brother @rishipr , thank you for your reply! I have realized now that some of these dependencies I probably don't need on production, so can you maybe help me with identifying what are those? 

At the moment, I'm unable to run this app locally because for example it says that I need "babel-eslint": "10.0.1" (among others) and I have 9.0.0, but when I install that version (10.0.1) then Heroku gives me error when I try to deploy app that it needs version 9.0.0... So confusing! Same goes for some other packages (babel-jest, babel-loader, eslint etc.). Do you know how to fix this brother?

Thanks a lot!

**Comment by rishipr** [comment]
Not sure how to fix this, never run into it myself. The only devDependency is nodemon, but that shouldn't be interfering with any production deployments. Let me know if you end up figuring it out.

**Comment by efendic** [comment]
In the end, I made another package.json file for dev and in it, I've put different versions needed for dev... so when I'm doing development, I'm using that file and rename the production file to package_prod.json and then when I wanna deploy, I rename the dev file to package_dev.json and the prod to package.json... I know it's not optimal, but it works :) 

Thank you for this fine boilerplate app!
