### ISSUE TITLE
Remove footer

### ISSUE THREAD

**Issue by efendic** [rishipr/mern-auth#8]
Hello brother,

I hope this question will be simple for you: How do I remove the footer on my app? I used your code as a boilerplate, I'm building a "Challenge" app. Here's the screenshot of what I mean:

https://i.imgur.com/kHY9PI4.png

Down there where the mouse is, there is nothing, just empty space. I've tried inspecting the site to see where is this space, but can't even access it. Can you help me with this please?

Thank you for this fine code and all the best!

**Comment by rishipr** [comment]
Can't be sure without seeing the code, but I would install React dev tools and try to inspect with that to see if there is an extra component down there. Also, check out the CSS of the page. Usually, inspect mode should give it away (either an extra component or some CSS that shouldn't be there). Maybe the CSS height for that page is hardcoded in which case the content would be cutoff past that point. Hopefully, you can solve it!
